export const CODE_GENERATION_STATUS = Object.freeze({
  READY: "READY",
  NEEDS_CONTEXT: "NEEDS_CONTEXT",
  SAFETY_BLOCKED: "SAFETY_BLOCKED",
  INVALID: "INVALID"
});

export const CODE_GENERATION_TOOL = Object.freeze({
  WRITE_FILE: "WRITE_FILE",
  APPLY_PATCH: "APPLY_PATCH"
});

export const CODE_GENERATION_LOG_EVENTS = Object.freeze({
  START: "CODE_GENERATION_START",
  CONTEXT_BUILT: "CODE_CONTEXT_BUILT",
  CONVENTION_RESOLVED: "CODE_CONVENTION_RESOLVED",
  FILE_GENERATED: "CODE_FILE_GENERATED",
  PATCH_GENERATED: "CODE_PATCH_GENERATED",
  IMPORTS_RESOLVED: "CODE_IMPORTS_RESOLVED",
  EXPORTS_RESOLVED: "CODE_EXPORTS_RESOLVED",
  TEST_GENERATED: "CODE_TEST_GENERATED",
  SAFETY_BLOCKED: "CODE_SAFETY_BLOCKED",
  NEEDS_CONTEXT: "CODE_NEEDS_CONTEXT",
  COMPLETE: "CODE_GENERATION_COMPLETE"
});

