export function createPlanningContextSnapshot(context) {
  if (!context) return null;

  const facts = context.facts || context.projectScan || {};
  const derived = context.derived || {};
  return {
    facts: {
      ...facts
    },
    derived: {
      verifiedFramework: derived.verifiedFramework || context.verifiedFramework,
      verifiedPackageManager: derived.verifiedPackageManager || context.verifiedPackageManager,
      verifiedValidation: derived.verifiedValidation || context.verifiedValidation,
      requiredFramework: derived.requiredFramework || context.requiredFramework || null,
      planningStrategyGraph: derived.planningStrategyGraph || context.planningStrategyGraph || null,
      verifiedFiles: [...context.verifiedFiles],
      verifiedCommands: [...context.verifiedCommands],
      verifiedRecommendations: [...context.verifiedRecommendations],
      blockedRecommendations: [...context.blockedRecommendations],
      workspaceCapabilities: [...(context.workspaceCapabilities || [])],
      artifactCandidates: [...(context.artifactCandidates || [])],
      artifactGraph: context.artifactGraph || null,
      artifactOperations: { ...(context.artifactOperations || {}) },
      plannerApprovedArtifacts: [...(context.plannerApprovedArtifacts || [])],
      artifactOwnership: { ...(context.artifactOwnership || {}) },
      artifactLifecycle: { ...(context.artifactLifecycle || {}) },
      operationPlan: [...(context.operationPlan || [])],
      capabilityEvidence: [...(context.capabilityEvidence || [])],
      objectiveConstraints: [...(context.objectiveConstraints || [])],
      planningStrategies: [...(context.planningStrategies || [])],
      initializationStrategies: [...(context.initializationStrategies || [])],
      implementationStrategies: [...(context.implementationStrategies || [])],
      implementationVariants: [...(context.implementationVariants || [])],
      selectedImplementation: context.selectedImplementation || null,
      implementationEvidence: [...(context.implementationEvidence || [])],
      implementationPolicyDecision: context.implementationPolicyDecision || null,
      implementationVariantGraph: context.implementationVariantGraph || null,
      satisfiedCapabilities: [...(context.satisfiedCapabilities || [])],
      missingCapabilities: [...(context.missingCapabilities || [])],
      capabilityCoverage: context.capabilityCoverage || null,
      capabilityGapGraph: context.capabilityGapGraph || null,
      satisfiedCapabilityGraph: context.satisfiedCapabilityGraph || null,
      missingCapabilityGraph: context.missingCapabilityGraph || null,
      initializationCapabilities: [...(context.initializationCapabilities || [])],
      capabilitySatisfaction: context.capabilitySatisfaction || null
    },
    packageJsonFound: context.packageJsonFound,
    verifiedFileCount: context.verifiedFiles.length,
    blockedRecommendationCount: context.blockedRecommendations.length,
    verifiedCommandCount: context.verifiedCommands.length,
    verifiedFramework: context.verifiedFramework,
    requiredFramework: context.requiredFramework || null,
    planningStrategyGraph: context.planningStrategyGraph || null,
    workspaceCapabilityCount: (context.workspaceCapabilities || []).length,
    artifactCandidateCount: (context.artifactCandidates || []).length,
    artifactOperationCount: Object.keys(context.artifactOperations || {}).length,
    plannerApprovedArtifactCount: (context.plannerApprovedArtifacts || []).length,
    artifactOwnershipCount: Object.keys(context.artifactOwnership || {}).length,
    artifactLifecycleCount: Object.keys(context.artifactLifecycle || {}).length,
    operationPlanCount: (context.operationPlan || []).length,
    capabilityEvidenceCount: (context.capabilityEvidence || []).length,
    implementationStrategyCount: (context.implementationStrategies || []).length,
    implementationVariantCount: (context.implementationVariants || []).length,
    satisfiedCapabilityCount: (context.satisfiedCapabilities || []).length,
    missingCapabilityCount: (context.missingCapabilities || []).length,
    verifiedPackageManager: context.verifiedPackageManager,
    verifiedValidation: context.verifiedValidation,
    hasVerifiedFiles: context.hasVerifiedFiles,
    hasBlockedRecommendations: context.hasBlockedRecommendations,
    policies: { ...(context.policies || context.plannerPolicies || {}) },
    verifiedFiles: [...context.verifiedFiles],
    blockedFiles: context.blockedRecommendations.map(r => r.path).filter(Boolean),
    verifiedCommands: [...context.verifiedCommands]
  };
}
