export const EXECUTION_PLAN_VERSION = 1;
export const EXECUTION_PLAN_FILE = "execution-plan.json";

export const EXECUTION_LOG_EVENTS = {
  START: "EXECUTION_PLAN_START",
  TASK_CREATED: "EXECUTION_TASK_CREATED",
  DEPENDENCY_CREATED: "EXECUTION_DEPENDENCY_CREATED",
  DAG_VALIDATED: "EXECUTION_DAG_VALIDATED",
  CRITICAL_TASK_LOCKED: "EXECUTION_CRITICAL_TASK_LOCKED",
  VALIDATION_PLANNED: "EXECUTION_VALIDATION_PLANNED",
  RISK_ANALYZED: "EXECUTION_RISK_ANALYZED",
  SCOPE_GUARD_APPLIED: "EXECUTION_SCOPE_GUARD_APPLIED",
  FINALIZATION_BLOCKED: "EXECUTION_FINALIZATION_BLOCKED",
  RETRY_PLANNED: "EXECUTION_RETRY_PLANNED",
  PLAN_SERIALIZED: "EXECUTION_PLAN_SERIALIZED",
  PLAN_RESUMED: "EXECUTION_PLAN_RESUMED",
  PLAN_COMPLETE: "EXECUTION_PLAN_COMPLETE"
};

export const EXECUTION_TASK_STATUS = Object.freeze({
  PENDING: "PENDING",
  READY: "READY",
  RUNNING: "RUNNING",
  DONE: "DONE",
  FAILED: "FAILED",
  BLOCKED: "BLOCKED",
  SKIPPED: "SKIPPED",
  RECOVERING: "RECOVERING"
});

export const EXECUTION_TASK_KIND = Object.freeze({
  INSPECT: "inspect",
  READ: "read",
  CREATE: "create",
  MODIFY: "modify",
  DELETE: "delete",
  RENAME: "rename",
  VALIDATE: "validate",
  RECOVER: "recover",
  DOCUMENT: "document",
  FINALIZE: "finalize"
});

export const EXECUTION_ALLOWED_TOOLS = [
  "READ_FILE",
  "WRITE_FILE",
  "APPLY_PATCH",
  "RUN_TERMINAL",
  "LIST_FILES",
  "SEARCH_FILES",
  "VALIDATE",
  "FINAL"
];
